"""Add Course and Section

Revision ID: 967608827e8f
Revises: daa26bfc263d
Create Date: 2016-02-27 20:02:53.811961

"""

# revision identifiers, used by Alembic.
revision = '967608827e8f'
down_revision = 'daa26bfc263d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.Column('semester', sa.Enum('Fall', 'Interterm', 'Spring', 'Summer'), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section')
    op.drop_table('course')
    ### end Alembic commands ###
